CREATE PROCEDURE dbo.CreateUser
(
	@User dbo.UDT_Users READONLY
)
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	
	DECLARE @InsertedObjects UDT_Ids
	
		INSERT INTO dbo.Users
		OUTPUT INSERTED.Id INTO @InsertedObjects 
		SELECT * 
		FROM @User

	SELECT Obj.Id
	FROM @InsertedObjects AS Obj

END